package com.gigya.socialize.android.event;

import com.gigya.socialize.GSObject;

/**
 * Listener for events generated by GSAPI.showAddConnectionsUI
 */
public interface GSConnectUIListener extends GSUIListener {

    /**
     * Successful adding connection occurred
     *
     * @param provider - the name of the provider to which the user added connection (e.g. "Facebook").
     * @param user     - an object containing updated information for the current user.
     * @param context  - the context object passed as a parameter to the method that triggered this event, or null if no object was passed.
     */
    public void onConnectionAdded(String provider, GSObject user, Object context);
}
