package com.gigya.socialize.android.event;

import com.gigya.socialize.GSObject;

/**
 * Listener for events generated by GSAPI.showLoginUI
 */
public interface GSLoginUIListener extends GSUIListener {
    /**
     * Successful login occurred
     *
     * @param provider - the name of the provider that the user used in order to login (e.g. "Facebook").
     * @param user     - an object containing updated information for the current user.
     * @param context  - the context object passed as a parameter to the method that triggered this event, or null if no object was passed.
     */
    public void onLogin(String provider, GSObject user, Object context);
}
