package com.gigya.socialize.android.event;

import com.gigya.socialize.GSResponse;

/**
 * Listener for events generated by GSAPI.showLoginUI and GSAPI.showAddConnectionsUI
 */
public interface GSUIListener {
    /**
     * Fired when the UI is shown
     *
     * @param context - the context object passed as a parameter to the method that triggered this event, or null if no object was passed.
     */
    public void onLoad(Object context);

    /**
     * Fired when the UI is closed
     *
     * @param canceled - indicates whether the operation (login/ add-connection) has canceled
     * @param context  - the context object passed as a parameter to the method that triggered this event, or null if no object was passed.
     */
    public void onClose(boolean canceled, Object context);

    /**
     * Fired when an error has occurred
     *
     * @param res     - a GSResponse object enfolding the error details
     * @param context - the context object passed as a parameter to the method that triggered this event, or null if no object was passed.
     */
    //		public abstract void onError(int errorCode, String errorMessage, String trace, Object context);
    public void onError(GSResponse res, Object context);

}
